### ISSUE TITLE
Results submission: "No such file or directory" error

### ISSUE THREAD

**Issue by Didayolo** [ihsaan-ullah/create_a_challenge#2]
Hi,

When uploading the competition and trying to upload the sample results submission, I obtain the following error:

```
Traceback (most recent call last):
  File "/worker/worker.py", line 353, in run
    bundles = get_bundle(cache_dir, root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 195, in get_bundle
    metadata[k] = get_bundle(cache_dir, bundle_path, k, v)
  File "/worker/worker.py", line 157, in get_bundle
    metadata_folder = _find_only_folder_with_metadata(bundle_path)
  File "/worker/worker.py", line 48, in _find_only_folder_with_metadata
    files_in_path = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/codalab/tmplWhWJS/run/hidden_ref'
```

**Comment by ihsaan-ullah** [comment]
This may occur because of no reference data.

Upload an empty zip as reference data and point to it in the competition settings. I hope this will solve the problem

**Comment by Didayolo** [comment]
Thanks for your answer. I think this should be fixed directly in the bundle as it is used in CodaLab's documentation.
